title: Conversation Journal
name: Conversational Journal
email: jennytkim@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog documenting interesting conversations with interesting people.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://conversationjournal.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Conversation Journal # add your name
author-pic: \images\jennykim.jpg

# Contact links
email: jennytkim@gmail.com
github: jennytkim
linkedin: jennytkim # Add your Email address


# Newsletter
mailchimp: https://conversationjournal.us12.list-manage.com/subscribe/post?u=8458bec01aeeec8bdfe207811&amp;id=98874e96cf # Add your MailChimp form identifier.

# Disqus
discus_identifier: conversationjournal # Add your discus identifier

# Tracker
analytics: UA-113700903-1 # Google Analytics

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
