title: Conversation Journal
email: jennytkim@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog documenting interesting conversations with interesting people.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://conversationjournal.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Conversation Journal # add your name
author-pic: \images\jennykim.jpg
about-author: Hey! I'm Jenny. Thanks for checking out my blog. This blog/personal project transpired from my hate for small talk and love for people’s stories. Through this project, I want to meet interesting people, have meaningful conversations with them, and share their compelling stories. Please reach out to me if you have stories to share, know someone who has some crazy stories, or just want to chat! I’m always up for great conversation.


# Contact links
email: jennytkim@gmail.com
github: jennytkim
linkedin: jennytkim # Add your Email address


# Newsletter
mailchimp: https://conversationjournal.us17.list-manage.com/subscribe/post?u=b46e3ad73a11a9a39cf27a9a5&amp;id=778332854b # Add your MailChimp form identifier.

# Disqus
discus_identifier: conversationjournal # Add your discus identifier

# Tracker
analytics: UA-113700903-1 # Google Analytics

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
